export default {
  SUCCESSFUL: '0',
  FAILED: '1',
  PENDING: '2',
  REFUNDED: '10',
  AUTHORIZED: '15',
  CAPTURED: '16',
  REVERSAL_PENDING: '31',
  REVERSED: '9',
  TRANSACTION_DOES_NOT_EXIST: '-1',
  INTERNAL_SYSTEM_ERROR: '-2'
}
